### ISSUE TITLE
Maybe add a note about doc-comment?

### ISSUE THREAD

**Issue by GuillaumeGomez** [budziq/rust-skeptic#103]
Now that the [doc-comment](https://crates.io/crates/doc-comment) crate is out and allows to check markdown files examples as well using rustdoc, maybe put a note about it? It has the advantage to be a lot smaller and doesn't generate files or make `cargo` rebuilds crate every time.

**Comment by budziq** [comment]
Hi @GuillaumeGomez, thanks for the info, it looks really promising. I currently do not have capacity to checkout doc-comment in upcoming days but I'd be more than willing to accept a PR to the readme mentioning alternative solutions!
