### ISSUE TITLE
Running tests on windows ignores dependencies

### ISSUE THREAD

**Issue by ilslv** [budziq/rust-skeptic#131]
While setting up windows CI job in [cucumber](https://github.com/cucumber-rs/cucumber) crate I've stumbled into a strange issue: windows target cannot find any crates.io dependencies, while ubuntu and macOS are working just fine. 

I've also created a [repository with a MRE](https://github.com/ilslv/skeptic-mre). There is also a [PR showing that this issue is present only for dependencies from crates.io](https://github.com/ilslv/skeptic-mre/pull/1)

**Comment by djc** [comment]
Hey @ilslv, thanks for reporting! Unfortunately I don't really have a use case for skeptic right now and I'm pretty busy, so I don't have much time/energy to spend on it. Happy to review code if you manage to find a fix, though!
