### ISSUE TITLE
Consider setting the cwd when running tests

### ISSUE THREAD

**Issue by brson** [budziq/rust-skeptic#23]
Write now when tests are executing the cwd seems to be set to the directory of the cargo project. This means that examples that do file I/O write to this directory. Seems like the test runner could set the cwd to an appropriate temporary directory to make that 'just work'.

**Comment by budziq** [comment]
@brson  it was closed by https://github.com/brson/rust-skeptic/issues/26
I have forgotten to add "fixes" clause to PR. Sorry.
