### ISSUE TITLE
Add information and example how to use the crate with multiple files.

### ISSUE THREAD

**Issue by iddm** [budziq/rust-skeptic#28]
I have just found this crate by help of the community. I have a book written with `mdbook` and I want to compile it's code for testing. I see the code in the readme of this crate:

    skeptic::generate_doc_tests(&["README.md"]);

From what I see here: the function takes a slice to an array of string slices, which are files to parse.
I would like to have a new function which can take a mask of files (for `book/src/*.md`). Or is there a better way which everyone uses already?

**Comment by budziq** [comment]
Hi @vityafx,

Please see how multiple files are handled in [rust-cookbook](https://github.com/brson/rust-cookbook/blob/master/build.rs). Nothing fancy there, it's already pretty simple.

I guess that you are welcome to submit a PR describing and improving the multi file handling.

**Comment by iddm** [comment]
Hi @budziq ! Unfortunately, ends_with did not work for me, so I did it in [another way](https://github.com/vityafx/toornament-rs/blob/master/external_markdown_tests/build.rs): it recursively walks over a given directory and looks for md files.

And yes, making a PR is in my todo list.

**Comment by budziq** [comment]
@vityafx than you might be interested in nice `glob` crate https://github.com/rust-lang-nursery/glob that should match most of your needs. your usecase should should boil down to 2-3 lines then.

**Comment by bozaro** [comment]
Listing files by wildcard is conflicted by cargo incremental compilation login.
See: https://github.com/rust-lang/cargo/issues/4213

**Comment by iddm** [comment]
@bozaro Dont quite understand what you are trying to say. I have tested my PR a lot of times with changing files, everything was good. The only problem I had was the same as without my glob patch - the compiler found few built libraries so it could not decide what to take from them for linking, however, running cargo clean fixed this everytime.

**Comment by bozaro** [comment]
Unfortunatelly cargo don't track file list for incremental compilation.
For example:
```
$ cat build.rs 
extern crate skeptic;

fn main() {
    skeptic::markdown_files_of_directory("foo/");
}
$ cargo build
   Compiling rust-foo v0.1.0 (file:///home/bozaro/github/rust-foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.41 secs
$ echo > foo/A.md
$ echo > foo/B.md
$ echo > foo/C.md
$ cargo build
   Compiling rust-foo v0.1.0 (file:///home/bozaro/github/rust-foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.44 secs
$ rm foo/A.md 
$ cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.1 secs
$ rm foo/B.md 
$ cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.1 secs
$ rm foo/C.md
$ cargo build
   Compiling rust-foo v0.1.0 (file:///home/bozaro/github/rust-foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.43 secs
```
Cargo don't rebuild project after removing files `foo/A.md` and `foo/B.md`, because it store only max file mtime timestamp (for latest file `foo/C.md`).
This issue also affects `.skt.md` files :(
