### ISSUE TITLE
regression in "#" (hidden code handling)

### ISSUE THREAD

**Issue by budziq** [budziq/rust-skeptic#42]
Rust cookbook fails `cargo test` due to regression in "#" (hidden code handling)
```
error: expected `[`, found `error_chain`
 --> /tmp/rust-skeptic.VR6uMVYZzYjL/test.rs:7:1
  |
7 | error_chain! {
  | ^^^^^^^^^^^

error: aborting due to previous error

test app_sect_compress_a_directory_into_tarball_line_195 ... FAILED
error: expected `[`, found `error_chain`
 --> /tmp/rust-skeptic.qqfIPuVHxIRO/test.rs:8:1
  |
8 | error_chain! {
  | ^^^^^^^^^^^
```

The single `#` without following space is no longer removed. So rustc expects to find `[` begining of an attribute but finds `error_chain! {` instead
```rust
use url::{Url, Position};
#
# error_chain! {
#     foreign_links {
#         UrlParse(url::ParseError);
#     }
# }
```

This is caused by https://github.com/brson/rust-skeptic/pull/40 unfortunately the pull was merged without proper testing.
cc @Chris--B

**Comment by budziq** [comment]
fixed by https://github.com/brson/rust-skeptic/commit/54841cf789ad787ba3b638267fdc851cea5f7f65

**Comment by Chris--B** [comment]
My apologies. I wasn't sure if that test case was important and whether rustdoc behaved that way, so I asked about it with my PR. Next time, I'll ask before submitting instead of asking with the PR.

Glad to see you were able to fix this quickly.

**Comment by budziq** [comment]
Hi @Chris--B 

Please do not feel discouraged! Going with PR first was wery good idea and you even asked about the case in the PR. The problem was entirely on maintainer side this time (we were in a hurry to close all PR's and this is always a bad idea).

The only thing to keep in mind is that some wonky tests are usually there for a reason (although that one was not named wery well).

Please feel free to submit more PR's in the future. Your contributions are very welcome! 👍
