### ISSUE TITLE
Skeptic explodes with file not found

### ISSUE THREAD

**Issue by frankmcsherry** [budziq/rust-skeptic#44]
Pretty sure I followed the instructions correctly, and then point it at a directory containing `mdbook` source. The paths look correct up until the last SUMMARY.md; no clue where that comes from. In any case, ideally there wouldn't be a panic, and even better if it reported which file it was having the hard time opening I could try and debug it! :D

```
Echidnatron% cargo build
   Compiling timely v0.2.0 (file:///Users/mcsherry/Projects/timely-dataflow)
error: failed to run custom build command for `timely v0.2.0 (file:///Users/mcsherry/Projects/timely-dataflow)`
process didn't exit successfully: `/Users/mcsherry/Projects/timely-dataflow/target/debug/build/timely-39b1af5e40cc46aa/build-script-booktests` (exit code: 101)
--- stdout
cargo:rerun-if-changed=mdbook/src/SUMMARY.md
cargo:rerun-if-changed=mdbook/src/SUMMARY.md.skt.md
cargo:rerun-if-changed=mdbook/src/chapter_1.md
cargo:rerun-if-changed=mdbook/src/chapter_1.md.skt.md
cargo:rerun-if-changed=mdbook/src/chapter_1_1.md
cargo:rerun-if-changed=mdbook/src/chapter_1_1.md.skt.md
cargo:rerun-if-changed=mdbook/src/chapter_1_2.md
cargo:rerun-if-changed=mdbook/src/chapter_1_2.md.skt.md
cargo:rerun-if-changed=mdbook/src/chapter_1_3.md
cargo:rerun-if-changed=mdbook/src/chapter_1_3.md.skt.md
cargo:rerun-if-changed=mdbook/src/chapter_2.md
cargo:rerun-if-changed=mdbook/src/chapter_2.md.skt.md
cargo:rerun-if-changed=mdbook/src/chapter_2_1.md
cargo:rerun-if-changed=mdbook/src/chapter_2_1.md.skt.md
cargo:rerun-if-changed=mdbook/src/chapter_2_2.md
cargo:rerun-if-changed=mdbook/src/chapter_2_2.md.skt.md
cargo:rerun-if-changed=mdbook/src/chapter_2_3.md
cargo:rerun-if-changed=mdbook/src/chapter_2_3.md.skt.md
cargo:rerun-if-changed=mdbook/src/chapter_2_4.md
cargo:rerun-if-changed=mdbook/src/chapter_2_4.md.skt.md
cargo:rerun-if-changed=mdbook/src/chapter_3.md
cargo:rerun-if-changed=mdbook/src/chapter_3.md.skt.md
cargo:rerun-if-changed=mdbook/src/chapter_4.md
cargo:rerun-if-changed=mdbook/src/chapter_4.md.skt.md
cargo:rerun-if-changed=mdbook/src/chapter_4_1.md
cargo:rerun-if-changed=mdbook/src/chapter_4_1.md.skt.md
cargo:rerun-if-changed=mdbook/src/chapter_4_2.md
cargo:rerun-if-changed=mdbook/src/chapter_4_2.md.skt.md
cargo:rerun-if-changed=mdbook/src/introduction.md
cargo:rerun-if-changed=mdbook/src/introduction.md.skt.md
cargo:rerun-if-changed=SUMMARY.md
cargo:rerun-if-changed=SUMMARY.md.skt.md

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Echidnatron% 
```

**Comment by frankmcsherry** [comment]
Ah, in case it helps, here is the `booktest.rs` I'm using (`build.rs` is apparently special now, and I was confused for a while when removing `build = "build.rs"` from `Cargo.toml` didn't stop the crashing).

```rust
extern crate skeptic;

use skeptic::*;

fn main() {
    // skeptic::generate_doc_tests(&["mdbook/src/chapter_1_1.md"]);
    let mut mdbook_files = markdown_files_of_directory("mdbook/src");
    mdbook_files.push("SUMMARY.md".to_owned());
    generate_doc_tests(&mdbook_files);
}
```

Everything seems to go fine with just the commented out line; it seemed to take a minute or so and hadn't finished, but no error.

**Comment by frankmcsherry** [comment]
Oh wait. I think I now understand. The example which does this is not setting a directory and then providing a file in that directory, it just building a list of files to which I add some non-existent file, rather than the root of the markdown files in the directory specified.

**Comment by budziq** [comment]
Hi. If you have any further problems please push your problematic repo somewhere to a branch and I'll try to troubleshoot. (I did not mention I co-maintain skeptic too ;))

**Comment by frankmcsherry** [comment]
I .. think this is attributable to "user error". Though, I suspect the example could have some comments explaining what each of the lines does, in the aim of minimize the volume of future user error.

As another minor issue: `build.rs` is a reserved filename that Cargo will build even without a `build = "build.rs"` line in Cargo.toml, and even *despite* a `#build = "build.rs"` line in Cargo.toml, which caused the debugging process to take longer than I hoped. 

I'm not sure what advice to give in the instructions, but several things lead me to a state where the only way to fix things was to delete all references to skeptic, which I suspect is not intended. :D

**Comment by budziq** [comment]
Hmm, If you have any loose thoughts regarding how the description could be improved or what made it finally "click" I'll gladly accept PR (or even some unformatted ideas that I'll use to make the description better) :)

If the setup works, I'll close the issue :)

**Comment by frankmcsherry** [comment]
PR incoming. Set-up works as intended now, once I understood things a bit better.
