### ISSUE TITLE
skeptic tests names should  contain line number of test begining instead of end

### ISSUE THREAD

**Issue by budziq** [budziq/rust-skeptic#47]
Currently the test names generated by skeptic have following form:
```rust
format!("{}_sect_{}_line_{}", file_stem, section, line_number)
```
or in case there is no parent markdown `section` 
```rust
format!("{}_line_{}", file_stem, line_number)
```
eg `readme_sect_skeptic_templates_line_192`

The `line_number` corresponds to the number of the last line in the tested code block. Which is confusing at best. The line numbers should correspond to the first line of the code block.

**Comment by Borginator** [comment]
pull request submitted :)

**Comment by budziq** [comment]
closed via https://github.com/budziq/rust-skeptic/pull/55

Thanks!
