### ISSUE TITLE
Unused dependencies are being passed on to clients

### ISSUE THREAD

**Issue by epage** [budziq/rust-skeptic#63]
skeptic uses pulldown-cmark for markdown parsing.  The dependency pulls in the [default features](https://github.com/budziq/rust-skeptic/blob/master/src/skeptic/Cargo.toml#L20). 

Unfortunately, pulldown-cmark declares [getopt as a default feature feature](https://github.com/google/pulldown-cmark/blob/master/Cargo.toml#L22).

**Comment by budziq** [comment]
Thanks!

Should be fixed with [0.13.1](https://crates.io/crates/skeptic/0.13.1) released to crates.io.
