### ISSUE TITLE
Failing selftests on nightly 1.24 windows MSVC builds.

### ISSUE THREAD

**Issue by budziq** [budziq/rust-skeptic#72]
Skeptic fails self tests with recent nightly (1.24) on windows MSVC builds as it cannot find / link with `serde_derive` (which is typically so/dll as opposed to rlib).

[Link to appveyor](https://ci.appveyor.com/project/budziq/rust-skeptic/build/job/0fgco22d3mxv302p)

```
error[E0463]: can't find crate for `serde_derive` which `skeptic` depends on
 --> C:\Users\appveyor\AppData\Local\Temp\1\rust-skeptic.xTHyFOhM2mC8\test.rs:2:1
  |
2 | extern crate skeptic;
  | ^^^^^^^^^^^^^^^^^^^^^ can't find crate
error: aborting due to previous error
test readme_sect_getting_started_line_34 ... FAILED
test hashtag_test_line_45 ... ok
test readme_sect_getting_started_line_67 ... ignored
error[E0463]: can't find crate for `serde_derive` which `skeptic` depends on
 --> C:\Users\appveyor\AppData\Local\Temp\1\rust-skeptic.0ndspglQlDPV\test.rs:2:1
  |
2 | extern crate skeptic;
  | ^^^^^^^^^^^^^^^^^^^^^ can't find crate
error: aborting due to previous error
test readme_sect_getting_started_line_49 ... FAILED
```

**Comment by Ryman** [comment]
I'm unable to reproduce this on my Windows 7 64bit machine with either the nightly listed in the log from my PR `nightly-2017-12-24-x86_64-pc-windows-msvc ~ rustc 1.24.0-nightly (169929308 2017-12-23)` or the latest nightly `rustc 1.24.0-nightly (2dad872a2 2017-12-29)`. There doesn't seem to be anything special required to install listed in the appveyor setup so I'm unsure if I'm missing a step or not, I'm just `clean`ing, `build`ing and `test`ing.

**Comment by budziq** [comment]
Thanks for looking into this. The problem should be reproducible by just

```
git clone https://github.com/budziq/rust-skeptic.git
cd rust-skeptic
cargo test
```
Even on latest rustc 1.24.0-nightly (3f916bd30 2017-12-30)
Historically Win 7 behaved differently (had less problems) than Win 10 which is used by appveyor build. I guess that this is another case where the differences surface. I'll not have access to a windows 10 box for the upcoming few days (and debugging via appveyor is less than ergonomic).

**Comment by budziq** [comment]
looks like the problem is nonexistent on latest 0.13.3 with rust 1.26
