### ISSUE TITLE
What's the minimum supported rustc version?

### ISSUE THREAD

**Issue by behnam** [budziq/rust-skeptic#85]
In UNIC, we've been maintain support for Rust 1.22.0, but the build recently started to fail because a build error from skeptic (https://travis-ci.org/open-i18n/rust-unic/jobs/417777108):

```rust
error[E0599]: no method named `to_ascii_lowercase` found for type `&str` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/skeptic-0.13.3/lib.rs:315:7
    |
315 |     s.to_ascii_lowercase()
    |       ^^^^^^^^^^^^^^^^^^
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            candidate #1: `use std::ascii::AsciiExt;`
    = help: did you mean `to_lowercase`?
```

I see the lowest version in `travis.yml` here is `stable`. Would be great to add some explicit version there and keep track of minimum version supported, so external libraries can depend on.

What do you think?

**Comment by budziq** [comment]
Hi @behnam! This line sure is problematic, it either errors on older rust or its alternative (proposed by tue compiler in your log) gives a verbose warning on newer ones.

Indeed I'd be interested in both:
- making the skeptic accessble for wider range of rust versions (ideally without warnings)
- providing clear info of minimal rust version  checked by CI

Unfortunately I'm more than tied reacently so can't say when I'd have time to touch the subject :(

On the other hand I'd hapilly accept PR's anytime!

**Comment by behnam** [comment]
Coo, @budziq! Submitted a PR (GH-86) to add explicit minimum-rust-version to the CI.
