### ISSUE TITLE
cargo_metadata v0.7

### ISSUE THREAD

**Issue by igor-raits** [budziq/rust-skeptic#94]
It would be huge help if you would be able to port skeptic to cargo_metadata 0.7.x.

Thanks!

**Comment by budziq** [comment]
Looks like cargo_metadata has completely changed their api for some reason. I'll look into it but no promises about the timeframe. But I'm game for any PR's too :)

**Comment by igor-raits** [comment]
Yesterday I was about to send PR, but they changed how workspaces are handled. Now they return PackageId which you can track back to Package... But that one does not contain URL and I could not find any way how to get that URL.

**Comment by budziq** [comment]
Yep after a brief skim over the API it looks like this key functionality was lost since cargo_metadata 0.7.
At this point I'm unwilling to return to hand parsing so I'll stick to 0.6 for now and open issue with cargo_metadata.

**Comment by budziq** [comment]
Ok using cargo_metadata v0.7 is feasible without handparsing https://github.com/budziq/rust-skeptic/pull/99 but cargo_metadata started using slightly newer compiler features which causes our CI on rust 1.24 to fail. I'll need to bump minimal rust version to 1.26 which in my book warrants bumping skeptic to 1.14.0
